# Generated by Django 3.0.3 on 2020-07-31 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='Option5',
        ),
    ]
